# Generated by Django 2.2.4 on 2019-08-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(blank=True, max_length=30, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('info', models.TextField(blank=True, max_length=200)),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
