# Generated by Django 2.2.4 on 2019-08-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='positions',
            new_name='position',
        ),
    ]
