# Generated by Django 2.2.4 on 2019-08-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190809_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название')),
                ('scope', models.CharField(blank=True, max_length=30, verbose_name='Сфера деятельности')),
                ('info', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
            ],
        ),
    ]
