# Generated by Django 2.2.4 on 2019-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190809_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='form',
            field=models.CharField(choices=[('Индивидуальный предприниматель', 'Закупки'), ('Производство', 'Производство'), ('Продажи', 'Продажи'), ('Строительство', 'Строительство'), ('Кредит', 'Кредит')], default='Закупки', help_text='Текущий ход', max_length=15, verbose_name='Тип такта'),
        ),
    ]
