# Generated by Django 2.2.4 on 2019-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_company_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='form',
            field=models.CharField(choices=[('Индивидуальный предприниматель', 'Индивидуальный предприниматель'), ('Общество с ограниченной ответственностью', 'Общество с ограниченной ответственностью')], default='Индивидуальный предприниматель', help_text='Организационно-правовая форма предприятия', max_length=50, verbose_name='ОП форма'),
        ),
    ]
