# Generated by Django 2.2.4 on 2019-08-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description', models.CharField(max_length=30, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Не активен', 'Не активен'), ('Активен', 'Активен'), ('Завершен', 'Завершен')], default='Не активен', help_text='Статус проекта', max_length=15, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Profile', verbose_name='Ответственный')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description', models.CharField(max_length=30, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Не активна', 'Не активна'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], default='Не активна', help_text='Статус задачи', max_length=15, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Project', verbose_name='Проект')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Profile', verbose_name='Ответственный')),
            ],
        ),
    ]
