# Generated by Django 2.2.4 on 2019-08-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190822_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='scope',
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='ScopesInCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Company', verbose_name='Компания')),
                ('scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Scope', verbose_name='Сфера деятельности')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
