# Generated by Django 2.2.4 on 2019-08-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190823_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
