# Generated by Django 2.2.4 on 2019-08-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_dealtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainsOfGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'ordering': ['count'],
            },
        ),
    ]
