# Generated by Django 2.2.4 on 2019-08-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remainsofgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('form', models.CharField(choices=[('Индивидуальный предприниматель', 'Индивидуальный предприниматель'), ('Общество с ограниченной ответственностью', 'Общество с ограниченной ответственностью')], default='Индивидуальный предприниматель', help_text='Организационно-правовая форма предприятия', max_length=50, verbose_name='ОП форма')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('info', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
    ]
