# Generated by Django 2.2.4 on 2019-08-29 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190828_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='scope',
        ),
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DealType', verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=30, verbose_name='Описание'),
        ),
    ]
